name: kakao_flutter_sdk

packages:
  - packages/*
  - example

scripts:
  test:
    run: melos run update && melos exec --fail-fast --ignore="*example*" --dir-exists="test" -- flutter test
    description: Run all test codes

  format:
    run: dart format .
    description: Reformat all codes

  analyze:
    run: melos exec --ignore="*example*" -- flutter analyze --no-pub

  upgrade:
    run: melos exec -- flutter pub upgrade

  update:
    run: if test -d ./kakao-sdk-test-data; then cd kakao-sdk-test-data && git fetch && git pull; else git clone git@github.daumkakao.com:kops/kakao-sdk-test-data.git; fi
    description: Update Test Data

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: '>=3.19.0'
